apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: device-plugin-consumer
  labels:
    name: device-plugin-consumer
spec:
  containers:
  - name: pause
    image: busybox
    command: ["/bin/sleep", "1000"]
    resources:
      limits:
        extend-k8s.io/example: 1

# extend-k8s.io # Resource Namespace
# example: PluginName        

